/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adbo.ui;

/**
 *  Kelas ini digunakan untuk menampilkan profil kelompok yang membuat project game ini.
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    Controller c;
    
    public About(Controller c) {
        this.c = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Foto3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Foto2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        foto1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(280, 100, 700, 575));
        setMaximumSize(new java.awt.Dimension(700, 575));
        setPreferredSize(new java.awt.Dimension(700, 575));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 490, 110, 40);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GUI Design - Documenter");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 400, 160, 14);

        Foto3.setForeground(new java.awt.Color(255, 255, 255));
        Foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adbo/image/Ilham.jpg"))); // NOI18N
        getContentPane().add(Foto3);
        Foto3.setBounds(550, 260, 70, 90);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ferrari Arya");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 360, 90, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2008730013");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 380, 80, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ilham Bani Utama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 360, 100, 14);

        Foto2.setForeground(new java.awt.Color(255, 255, 255));
        Foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adbo/image/ArmandoDemas.jpg"))); // NOI18N
        getContentPane().add(Foto2);
        Foto2.setBounds(330, 230, 70, 100);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Armando Demas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 340, 100, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("2010730107");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 380, 70, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GUI Designer - Codder");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 400, 140, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2008730036");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 360, 80, 14);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Head Project - Level Designer");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 380, 180, 14);

        foto1.setForeground(new java.awt.Color(255, 255, 255));
        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adbo/image/FerrariArya.jpg"))); // NOI18N
        getContentPane().add(foto1);
        foto1.setBounds(80, 260, 70, 90);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Last Assignment of Oriented Object Analysis Design");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 650, 60);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adbo/image/AboutBG.jpg"))); // NOI18N
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 70, 700, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
        this.c.mainMenuFrame.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new About().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Foto2;
    private javax.swing.JLabel Foto3;
    private javax.swing.JLabel foto1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
